### ISSUE TITLE
function remove_policy() failed bug!!!

### ISSUE THREAD

**Issue by Brandon-lz** [drorvinkler/pycasbin-pony-adapter#1]
when I run the functino :e.delete_role_for_user('alice','admin'), I got an False return, but the policy (g alice admin) exist.
it is a bug I found in  adapter.py at line 87:
```python
r = delete(cr for cr in self.rule_cls
                   if cr.ptype == ptype and
                   cr.v0 == v(0) and cr.v1 == v(1) and
                   cr.v0 == v(2) and cr.v1 == v(3) and
                   cr.v0 == v(4) and cr.v1 == v(5)
                   )
```
this is a obvious mistack, it should be:
```python
r = delete(cr for cr in self.rule_cls
                   if cr.ptype == ptype and
                   cr.v0 == v(0) and cr.v1 == v(1) and
                   cr.v2 == v(2) and cr.v3 == v(3) and
                   cr.v4 == v(4) and cr.v5 == v(5)
                   )
```

**Comment by hsluoyz** [comment]
@drorvinkler

**Comment by drorvinkler** [comment]
Thank you, I have fixed the bug

**Comment by hsluoyz** [comment]
@drorvinkler saw it: https://github.com/drorvinkler/pycasbin-pony-adapter/commit/ed6c00349c327f5492fb890b347287cea1e800c4

Thanks! Can you make a new release in pypi?

**Comment by drorvinkler** [comment]
Already did:
https://pypi.org/project/casbin-pony-adapter/1.0.1/
